plugins {
    `kotlin-dsl`
    id("dev.cherrypizza.mc-server-kit-publish")
}

repositories {
    mavenCentral()
    gradlePluginPortal()
    maven("https://repo.papermc.io/repository/maven-public/")
}

java {
    withSourcesJar()
}

dependencies {
    // Делает version-catalog accessor (LibrariesForLibs) доступным внутри
    // precompiled-script-плагинов (.base/.minecraft используют `the<LibrariesForLibs>()`).
    compileOnly(files(libs::class.java.protectionDomain.codeSource.location))

    implementation("org.jetbrains.kotlin:kotlin-gradle-plugin:${libs.versions.kotlin.get()}")
    implementation("io.micronaut.gradle:micronaut-minimal-plugin:${libs.versions.micronaut.plugin.get()}")
    implementation("com.google.devtools.ksp:com.google.devtools.ksp.gradle.plugin:${libs.versions.ksp.get()}")
    implementation("de.eldoria.plugin-yml.paper:de.eldoria.plugin-yml.paper.gradle.plugin:${libs.versions.plugin.yml.get()}")
    implementation("com.gradleup.shadow:com.gradleup.shadow.gradle.plugin:${libs.versions.shadow.get()}")
    // paperweight НЕ тянем: платформа (paper-api / paperweight) — уровень потребителя.

    // YamlUtils — мерж слоёв template_variables.yml
    implementation("org.snakeyaml:snakeyaml-engine:${libs.versions.snakeyaml.engine.get()}")
}

// McServer.VERSION не хардкодится отдельно: генерируем const из project.version
// (его задаёт конвенция .publish). Единственная точка правки версии — там.
val generateMcServerVersion by tasks.registering {
    val outputDir = layout.buildDirectory.dir("generated/sources/mcserver-version/kotlin")
    val pluginVersion = project.version.toString()
    inputs.property("version", pluginVersion)
    outputs.dir(outputDir)
    doLast {
        outputDir.get().file("McServerVersion.kt").asFile.apply {
            parentFile.mkdirs()
            writeText(
                "// GENERATED by :gradle-plugin (generateMcServerVersion). Не редактировать.\n" +
                    "internal const val MC_SERVER_VERSION: String = \"$pluginVersion\"\n"
            )
        }
    }
}

sourceSets {
    main {
        kotlin.srcDir(generateMcServerVersion)
    }
}